# Use a base image
FROM python:3.9

# Set the working directory
WORKDIR /app

# Copy project files to the container
COPY . .

# Install dependencies
RUN pip install -r requirements.txt

# Expose a port
EXPOSE 8000

# Define the startup command
CMD ["python", "app.py"]
