name: Linting

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4.2.2

    - name: setup python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
            pip install pre-commit black
            pre-commit install

    - name: run black
      run: black .

    - name: run pre-commit
      run: pre-commit run --all-files
    

    

    
